### ISSUE TITLE
有关微博营销助手功能的小建议

### ISSUE THREAD

**Issue by kylewuwu** [wenbinke/weiboyingxiao#1]
你好，非常感谢你开发的这个插件，用了一下感觉不错，在用的过程中感觉有2个地方不是很顺手，麻烦你这边能不能改进一下：

1  提取数据 那里 点开是进到  微博 搜索页面 ，如果能直接进到 微博搜索热搜榜（http://s.weibo.com/top/summary?cate=homepage） 就更好了

2 用户微博列表 页面 我用几个关键词搜索出来的用户，不是按 最新结果来排序的，要从最后往前翻页，这个能否改成 改成 按 最新结果 来排序。

再次感谢 ！

**Comment by kxbk100** [comment]
您好，我在使用过程中发现我的任务总是失败的，请问现在还可以正常使用吗？要如何解决这个问题呢？

**Comment by wenbinke** [comment]
排序问题已经解决了。
