### ISSUE TITLE
国产浏览器CRX_VERSION_NUMBER_INVALID

### ISSUE THREAD

**Issue by vayci** [wenbinke/weiboyingxiao#3]
你好！我在你的项目ghpages：http://wenbinke.github.io/weiboyingxiao 下载的已打包好的crx插件在低版本内核国产浏览器上会出现CRX_VERSION_NUMBER_INVALID错误。

我用该低版本内核浏览器对代码进行重新打包则可以解决该错误。

出现CRX_VERSION_NUMBER_INVALID错误的环境
浏览器：360极速浏览器9.0
内核版本：55.0

建议将ghpages上插件更换为能兼容低版本浏览器的crx，方便更多用户使用，谢谢！

**Comment by wenbinke** [comment]
国内浏览器没办法，目前只支持Chrome。等国内浏览器修复这个问题。
https://www.v2ex.com/t/413130
